version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    resource_class: small
    working_directory: ~/event-forwarder
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum ".go-version" }}-{{ checksum "go.sum" }}
            - deps-v1-{{ checksum ".go-version" }}-
            - deps-v1-
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          key: deps-v1-{{ checksum ".go-version" }}-{{ checksum "go.sum" }}
          paths:
            - ~/.cache/go-build
            - /go/pkg/mod
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test_ci
      - run:
          name: Enforce coverage
          command: make enforce
      - store_artifacts:
          path: coverage.out
